### ISSUE TITLE
Weird face when talking.

### ISSUE THREAD

**Issue by GonDragon** [Unknown-Anomaly/Peglaci#58]
Instead of doing a common talking animation when something is written on the chat, Peglaci characters make a weird gesture, opening its mouth, and fully opening both eyes from one side of its faces.
![image](https://user-images.githubusercontent.com/7538144/54776688-637e4f80-4bef-11e9-80f5-7e0992c7e5a3.png)

**Comment by HALLEYSHURA** [comment]
it's intentional; i wanted to make a sort of "hmmmm" expression with their talking/examine emote. i kinda got the impression from their examine dialogues that they were pretty smug around other races, so i wanted to reflect that. c:

https://puu.sh/DIkWJ/a567247d6a.png <-- little sketch of what i intended

i can change it if it's bothering anyone too much tho!

**Comment by GonDragon** [comment]
Oh, I see it now. Ok, then I close this issue.
